### ISSUE TITLE
Unable to find GoogleService-Info.plist

### ISSUE THREAD

**Issue by CearsKhush** [raghavbhasin97/Instagram-Clone#1]
Hey @raghavbhasin97 , I am trying to run your project but I am getting following error 

![Screenshot 2019-05-15 at 4 45 35 PM](https://user-images.githubusercontent.com/49678377/57771676-03a8ae80-7731-11e9-8408-4772b91a0226.png)
 
Should i need to create **GoogleService-Info.plist** by my own? 

Can you please help me with this?

**Comment by steventan93** [comment]
closed without any fixing ?

**Comment by CearsKhush** [comment]
I have created GoogleService-Info.plist file from my Firebase and that allows me to run the code
